// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mamun_SchoolApp.Data.EFCore;

namespace mamun_SchoolApp.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("mamun_SchoolApp.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("class_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            class_name = "KGI"
                        },
                        new
                        {
                            Id = 2,
                            class_name = "KGII"
                        },
                        new
                        {
                            Id = 3,
                            class_name = "Grade1"
                        },
                        new
                        {
                            Id = 4,
                            class_name = "Grade2"
                        });
                });

            modelBuilder.Entity("mamun_SchoolApp.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            name = "Oman"
                        },
                        new
                        {
                            Id = 3,
                            name = "Canada"
                        },
                        new
                        {
                            Id = 4,
                            name = "United Kindgom"
                        });
                });

            modelBuilder.Entity("mamun_SchoolApp.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CountryId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            CountryId = 1,
                            date_of_birth = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Peter Smith"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            CountryId = 2,
                            date_of_birth = new DateTime(2010, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "John Doe"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            CountryId = 3,
                            date_of_birth = new DateTime(2009, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Danny Doe"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 4,
                            CountryId = 4,
                            date_of_birth = new DateTime(2008, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Clark Smith"
                        });
                });

            modelBuilder.Entity("mamun_SchoolApp.Models.Students", b =>
                {
                    b.HasOne("mamun_SchoolApp.Models.Classes", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.HasOne("mamun_SchoolApp.Models.Countries", "Country")
                        .WithMany("Students")
                        .HasForeignKey("CountryId");

                    b.Navigation("Class");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("mamun_SchoolApp.Models.Classes", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("mamun_SchoolApp.Models.Countries", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
